version: '3'

tasks:

  default:
    cmds:
      - task --list

  run:
    desc: Run the development server
    cmds:
      - task: dev

  dev:
    desc: Run the development server
    cmds:
      - npm run dev

  install:
    desc: Install the project
    aliases: [i]
    cmds:
      - pnpm install

  build:
    desc: Build the project
    cmds:
      - npm run build:win

  test:
    desc: Run tests
    cmds:
      - npm test

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist out build
